name: normal

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go mod download

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1
        with:
          version: latest
          files: dist/speedtest-clash

      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: dist/speedtest-clash
